---
namespace: trippsc2
name: first_steps
version: 1.0.6
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains roles for performing first steps on freshly deployed machines.

license_file: 'LICENSE'

tags: []

dependencies:
  ansible.posix: ">=1.0.0"

repository: https://github.com/trippsc2/ansible-collection-first_steps.git

build_ignore:
  - .gitignore
