---
- name: Gather distribution facts
  when:
    - ansible_distribution is not defined or
      ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution

- name: Check if Fedora based distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Fedora"
    fail_msg: This role is only supported on Fedora.
    success_msg: This role is supported on Fedora.

- name: Warning for Fedora pre-41
  when:
    - ansible_distribution_major_version | int < 41
  ansible.builtin.debug:
    msg: This role is only tested on Fedora 41 and later. Versions prior to Fedora 41 may not work as expected.

- name: Install SETroubleshoot package
  become: true
  ansible.builtin.dnf:
    name:
      - setroubleshoot
    state: present

- name: Disable auditd service
  become: true
  ansible.builtin.systemd_service:
    name: auditd.service
    enabled: false

- name: Configure dnf to keep only 2 kernel versions
  become: true
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^installonly_limit='
    line: 'installonly_limit=2'
    state: present

- name: Disable hibernation
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true

- name: Reduce swappiness to 0
  become: true
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    reload: true

- name: Remove unnecessary services
  loop:
    - cockpit
    - dhcpv6-client
  become: true
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: disabled

- name: Update all packages
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_only: true
