---
- name: Check if Debian distribution
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"

- name: Install GPG utility
  become: true
  ansible.builtin.package:
    name:
      - gnupg
    state: present

- name: Install firewalld
  when:
    - debian_install_firewalld
  become: true
  ansible.builtin.package:
    name:
      - firewalld
    state: present

- name: Install ssl-cert package
  when:
    - debian_install_ssl_cert
  become: true
  ansible.builtin.package:
    name:
      - ssl-cert
    state: present

- name: Disable hibernation
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true

- name: Reduce swappiness to 0
  become: true
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    reload: true

- name: Update all packages
  become: true
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: true
  tags:
    - always
    - skip_ansible_lint
