---
argument_specs:
  main:
    short_description: Fedora First Steps
    description:
      - This role performs first steps on a freshly installed Fedora system.
    author: Jim Tarpley (@trippsc2)
    options: {}
