---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: ubuntu
  description: This role performs first steps on a freshly installed Ubuntu system.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

collections:
  - ansible.posix

dependencies: []
