---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: ubuntu
  description: This role performs first steps on a freshly installed Ubuntu system.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Ubuntu
      versions:
        - noble
        - jammy

collections:
  - ansible.posix

dependencies: []
