---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: rhel
  description: This role performs first steps on a freshly installed RHEL-based system.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: EL
      versions:
        - '9'
        - '8'

collections:
  - ansible.posix
  - community.general

dependencies: []
