---
argument_specs:
  main:
    short_description: Debian First Steps
    description:
      - This role performs first steps on a freshly installed Debian system.
    author: Jim Tarpley
    options:
      debian_install_firewalld:
        type: bool
        required: false
        default: true
        description:
          - Whether to install the firewalld package.
      debian_install_ssl_cert:
        type: bool
        required: false
        default: true
        description:
          - Whether to install the ssl-cert package.
