---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: debian
  description: This role performs first steps on a freshly installed Debian system.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

collections:
  - ansible.posix

dependencies: []
