---
name: Generate Role Docs - debian role
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-debian.yml
      - roles/debian/.aar_doc.yml
      - roles/debian/meta/argument_specs.yml
      - roles/debian/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.first_steps'
jobs:
  docs:
    name: Generate debian role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.first_steps'
      role_name: 'debian'
