---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/debian/.aar_doc.yml
      - roles/debian/README.md
      - roles/debian/meta/argument_specs.yml
      - roles/debian/meta/main.yml
      - roles/fedora/.aar_doc.yml
      - roles/fedora/README.md
      - roles/fedora/meta/argument_specs.yml
      - roles/fedora/meta/main.yml
      - roles/rhel/.aar_doc.yml
      - roles/rhel/README.md
      - roles/rhel/meta/argument_specs.yml
      - roles/rhel/meta/main.yml
      - roles/ubuntu/.aar_doc.yml
      - roles/ubuntu/README.md
      - roles/ubuntu/meta/argument_specs.yml
      - roles/ubuntu/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.first_steps'
jobs:
  docs_debian:
    name: Generate debian role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.first_steps'
      role_name: 'debian'
  docs_fedora:
    name: Generate fedora role documentation
    permissions:
      contents: write
    needs: docs_debian
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.first_steps'
      role_name: 'fedora'
  docs_rhel:
    name: Generate rhel role documentation
    permissions:
      contents: write
    needs: docs_fedora
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.first_steps'
      role_name: 'rhel'
  docs_ubuntu:
    name: Generate ubuntu role documentation
    permissions:
      contents: write
    needs: docs_rhel
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.first_steps'
      role_name: 'ubuntu'
